version: '3.8'

services:
  backup:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${BACKUP_SOURCE}:/data/source:ro
      - ${BACKUP_DIR}:/data/backups
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
